#!/usr/bin/env fish

# this pattern is to extract all include paths
# grep -o '/I "\([^ ]*\)"' < main.dsp | sort | uniq | sed -n 's/.*"\(.*\)"/\1/p'

set systemdir  (dirname (status --current-filename))/system
set styxnetdir (dirname (status --current-filename))/styxnet
set scriptdir (pwd)
set notfound
set notfound_src

echo "systemdir $systemdir"
echo "scriptdir $scriptdir"

for dsp in (find . | grep '\.dsp$' | grep -v 3rdparty)
  # echo $dsp

  set dirs (grep -o '/I "[^"]*"' < $dsp | sort | uniq | sed 's,^/I "\([^"]*\)".*$,\1,')

  # echo "dirs: $dirs"

  set folder (dirname $dsp)
  cd $folder
  for file in *.{h,cpp}
    for include in (sed -n 's/^#include "\([^"]*\)".*$/\1/p' $file)
      if test ! -f $include
        set found
        for dir in $dirs 
          set inc $dir/$include
          if test -f $inc
            if test -z $found
              set found $inc
              #echo "include \"$include\" in file $file is $inc"
              #TODO actually do something with the found include path
            else
              if /usr/bin/test $found -ef $inc
                #it dosn't matter at all
                echo "these files are the same: $found and $inc"
                set found $inc
              else
                pwd
                echo "already found $found, but got $inc"
                set found
                break
              end
            end
          end
        end
        if test -z $found
          if test -f $systemdir/$include
            set found $systemdir/$include
          else if test -f $styxnetdir/$include
            set found $styxnetdir/$include
          else
            set notfound $notfound "$include;$folder;$file"
            # echo "in dirs "$(tr '\n' ' ' <<< $dirs )
            # echo "in folder $folder"
            # pwd
            # else
          end
        end
      end
    end
  end
  cd -
end

for nf in $notfound
  set nfl (echo $nf | sed 'y/;/\n/')
  set include $nfl[1]
  set folder $nfl[2]
  set file $nfl[3]

  set found (find . | grep -i (echo $include | sed 's,^\(.*\)\.\(.*\)$,/\1\\\\.\2$,'))
  # TODO what happens for several hits?
  if test (count $found) -gt 1
    echo "ambigious $include in $folder/$file:"
    echo $found
  else if test (count $found) -lt 1
    echo "in $folder/$file can't resolve include $include"
  else
    # nothing to do here uniquely found a solution
    # TODO actually do something with the solution
  end
end


# for file in $(ag -l '#include ".*\.h"'); do
#   echo FILE $file FILE
#   for include in $(sed -n 's/#include "\(.*\.h\)"/\1/p' < $file); do
#     echo A $include
#     echo B $(ag -g $include)
#     #echo "s/\"$include\"/<$include>/"
# 
#   done
# done

